export const MENUS = {
  main: {
    text: '👋 ¡Hola! Bienvenid@ a *Urban Tech | Tecnología sin límites*.\nGracias por escribirnos. Será un gusto ayudarte a encontrar el equipo ideal para ti.\n\nContamos con:\n1️⃣ iPhone nuevos y exhibición\n2️⃣ Servicio técnico\n3️⃣ Plan retoma\n4️⃣ Medios de pago\n5️⃣ Redes sociales\n6️⃣ Ubicación\n\nCuéntanos qué equipo estás buscando o cómo podemos ayudarte. 😊',
    options: {
      1: 'iphones',
      2: 'servicio_tecnico',
      3: 'plan_retoma',
      4: 'medios_pago',
      5: 'redes_sociales',
      6: 'ubicacion',
    },
    keywords: {
      iphone: 'iphones',
      nuevo: 'iphones',
      nuevos: 'iphones',
      exhibicion: 'iphones',
      exhibición: 'iphones',
      expo: 'iphones',
      celular: 'iphones',
      celulares: 'iphones',
      apple: 'iphones',
      retoma: 'plan_retoma',
      plan: 'plan_retoma',
      cambiar: 'plan_retoma',
      cambio: 'plan_retoma',
      vender: 'plan_retoma',
      vendo: 'plan_retoma',
      pago: 'medios_pago',
      pagos: 'medios_pago',
      tarjeta: 'medios_pago',
      efectivo: 'medios_pago',
      nequi: 'medios_pago',
      daviplata: 'medios_pago',
      debito: 'medios_pago',
      débito: 'medios_pago',
      credito: 'medios_pago',
      crédito: 'medios_pago',
      addi: 'medios_pago',
      'siste credito': 'medios_pago',
      siste: 'medios_pago',
      banco: 'medios_pago',
      'banco bogota': 'medios_pago',
      'como pago': 'medios_pago',
      'forma de pago': 'medios_pago',
      tecnico: 'servicio_tecnico',
      técnico: 'servicio_tecnico',
      servicio: 'servicio_tecnico',
      reparacion: 'servicio_tecnico',
      reparación: 'servicio_tecnico',
      pantalla: 'servicio_tecnico',
      bateria: 'servicio_tecnico',
      batería: 'servicio_tecnico',
      daño: 'servicio_tecnico',
      dañado: 'servicio_tecnico',
      roto: 'servicio_tecnico',
      falla: 'servicio_tecnico',
      fallas: 'servicio_tecnico',
      problema: 'servicio_tecnico',
      problemas: 'servicio_tecnico',
      arreglo: 'servicio_tecnico',
      cargador: 'servicio_tecnico',
      carga: 'servicio_tecnico',
      audio: 'servicio_tecnico',
      micrófono: 'servicio_tecnico',
      microfono: 'servicio_tecnico',
      camara: 'servicio_tecnico',
      cámara: 'servicio_tecnico',
      redes: 'redes_sociales',
      instagram: 'redes_sociales',
      facebook: 'redes_sociales',
      tiktok: 'redes_sociales',
      social: 'redes_sociales',
      ig: 'redes_sociales',
      fb: 'redes_sociales',
      youtube: 'redes_sociales',
      twitter: 'redes_sociales',
      x: 'redes_sociales',
      siguenos: 'redes_sociales',
      seguir: 'redes_sociales',
      contacto: 'redes_sociales',
      ubicacion: 'ubicacion',
      ubicación: 'ubicacion',
      ubicados: 'ubicacion',
      donde: 'ubicacion',
      direccion: 'ubicacion',
      dirección: 'ubicacion',
      local: 'ubicacion',
      mapa: 'ubicacion',
      'donde quedan': 'ubicacion',
      'donde estan': 'ubicacion',
      'donde esta': 'ubicacion',
      'como llego': 'ubicacion',
      'que zona': 'ubicacion',
      barrio: 'ubicacion',
      municipio: 'ubicacion',
      tienda: 'ubicacion',
    },
  },
  iphones: {
    text: '📱 *iPhone nuevos y exhibición*\n\n¿Qué modelo te interesa?\n\n1️⃣ iPhone 17\n2️⃣ iPhone 16\n3️⃣ iPhone 15\n4️⃣ iPhone 13\n\nCuéntanos y te damos información al instante.\n\n0️⃣ Volver al menú principal',
    options: {
      1: 'iphone_17',
      2: 'iphone_16',
      3: 'iphone_15',
      4: 'iphone_13',
    },
    keywords: {
      17: 'iphone_17',
      'iphone 17': 'iphone_17',
      '17 pro max': 'iphone_17',
      '17 pro': 'iphone_17',
      'iphone 17 pro max': 'iphone_17',
      'iphone 17 pro': 'iphone_17',
      16: 'iphone_16',
      'iphone 16': 'iphone_16',
      '16 pro max': 'iphone_16',
      'iphone 16 pro max': 'iphone_16',
      'iphone 16 pro': 'iphone_16',
      15: 'iphone_15',
      'iphone 15': 'iphone_15',
      13: 'iphone_13',
      'iphone 13': 'iphone_13',
    },
  },
  iphone_17: {
    text: '📱 *iPhone 17*\n\n🔹 *iPhone 17 Nuevo Pro Max (256 GB)*\n• Cosmic Orange\n• Deep Blue\n• Silver\n\n🔹 *iPhone 17 Nuevo Pro (256 GB)*\n• Cosmic Orange\n• Deep Blue\n• Silver\n\n🔹 *iPhone 17 Nuevo (256 GB)*\n• Black\n• White\n• Lavender\n• Sage\n• Mystic Blue\n\n💬 Escribe *asesor* para hablar con un asesor\n\n0️⃣ Volver al menú principal',
  },
  iphone_16: {
    text: '📱 *iPhone 16*\n\n🔹 *iPhone 16 Exhibición Pro Max (256 GB)*\n• Black Titanium\n• White Titanium\n• Natural Titanium\n• Desert Titanium\n\n🔹 *iPhone 16 Exhibición (256 GB)*\n• Black\n• White\n• Pink\n• Teal\n• Ultramarine\n\n🔹 *iPhone 16 Nuevo (128 GB)*\n• Black\n• White\n• Pink\n• Teal\n• Ultramarine\n\n💬 Escribe *asesor* para hablar con un asesor\n\n0️⃣ Volver al menú principal',
  },
  iphone_15: {
    text: '📱 *iPhone 15*\n\n🔹 *iPhone 15 Nuevo (128 GB)*\n• Black\n• Blue\n• Green\n• Yellow\n• Pink\n\n💬 Escribe *asesor* para hablar con un asesor\n\n0️⃣ Volver al menú principal',
  },
  iphone_13: {
    text: '📱 *iPhone 13*\n\n🔹 *iPhone 13 Nuevo (128 GB)*\n• Midnight\n\n🔹 *iPhone 13 Exhibición (128 GB)*\n• Midnight\n• Green\n• Red\n\n🔹 *iPhone 13 Exhibición (256 GB)*\n• Blue\n• Pink\n\n💬 Escribe *asesor* para hablar con un asesor\n\n0️⃣ Volver al menú principal',
  },
  plan_retoma: {
    text: '🔄 *Plan Retoma*\n\n¿Tienes un iPhone que ya no usas?\n\n✅ Lo evaluamos al instante\n✅ Te damos crédito para tu nuevo equipo\n✅ Proceso rápido y seguro\n\n📸 Envíanos una foto de tu dispositivo y te damos una cotización al momento.\n\n💬 Escribe *asesor* para hablar con un asesor\n\n0️⃣ Volver al menú principal',
  },
  medios_pago: {
    text: '💳 *Medios de pago*\n\nAceptamos:\n\n💵 Efectivo\n💳 Tarjeta Débito\n💳 Tarjeta Crédito\n🏦 Addi\n🏦 SisteCredito\n🏦 Banco Bogotá\n\n¡Formas de pago pensadas para ti!\n\n0️⃣ Volver al menú principal',
  },
  servicio_tecnico: {
    text: '🔧 *Servicio técnico*\n\nOfrecemos servicio técnico especializado:\n\n📱 Reparación de celulares\n🔋 Cambio de batería\n🖥️ Cambio de pantalla\n📷 Reparación de cámara\n🔌 Reparación de puerto de carga\n💻 Problemas de software\n\n¿Qué servicio necesitas?\n\n💬 Escribe *asesor* para hablar con un asesor\n\n0️⃣ Volver al menú principal',
  },
  redes_sociales: {
    text: '📲 *Síguenos en redes sociales*\n\nInstagram:\nhttps://www.instagram.com/urbantech_col\n\nFacebook:\nhttps://www.facebook.com/share/1B76NNCD7K\n\nTikTok:\nhttps://www.tiktok.com/@urbantech_col\n\nPágina web:\nhttps://urbantechcol.com\n\n¡Síguenos para estar al día con nuestras ofertas y novedades! 🔥\n\n0️⃣ Volver al menú principal',
  },
  ubicacion: {
    text: '📍 *Ubicación*\n\nCra. 48 #10-45 Local 138\nCentro Comercial Monterrey, El Poblado, Medellín, Antioquia\n\n🕐 *Horario de atención:*\n• Lun–Sáb: 10:00 AM – 7:00 PM\n• Dom–Fes: 10:30 AM – 4:00 PM\n\n¡Te esperamos! 😊\n\n0️⃣ Volver al menú principal',
    location: {
      latitude: 6.214455535288204,
      longitude: -75.57732642057863,
    },
  },
};

export const MESSAGES = {
  defaultReply:
    'Lo siento, no entendí tu mensaje. Digita de nuevo la opción o escribe *menu* para ver las opciones disponibles. 😊',
  backToMain:
    '👋 ¡Hola! Bienvenido(a) a *Urban Tech | Tecnología sin límites*.\nGracias por escribirnos. Será un gusto ayudarte a encontrar el equipo ideal para ti.\n\nContamos con:\n1️⃣ iPhone nuevos y exhibición\n2️⃣ Servicio técnico\n3️⃣ Plan retoma\n4️⃣ Medios de pago\n5️⃣ Redes sociales\n6️⃣ Ubicación\n\nCuéntanos qué equipo estás buscando o cómo podemos ayudarte. 😊',
  sessionTimeout:
    '⏰ La sesión ha expirado por inactividad.\n\nSi necesitas ayuda, escríbenos de nuevo. ¡Estaremos aquí para ti! 😊',
  advisorRedirect: 'En breve un asesor se comunicará contigo. 😊',
};
